### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by derfredy** [w3f/polkadot-secure-validator#10]
Federico!! Muy fan tuyo @fgimenez !

Great collection of ansible / terraform codes. It is really amazing. I am using part of it, so thanks a million!
Is there any plan to include some monitoring?  Prometheus or similar
I cant find it.
Regards

**Comment by fgimenez** [comment]
> Federico!! Muy fan tuyo @fgimenez !

Vaya muchas gracias!! :D 

> Is there any plan to include some monitoring? Prometheus or similar

Monitoring is indeed a central concern for us. The approach we have taken so far is taking advantage of the current instrumentation of substrate-based applications which sends data to instances of substrate-telemetry https://github.com/paritytech/substrate-telemetry We have developed a Prometheus exporter https://github.com/w3f/substrate-telemetry-exporter that can be attached to a substrate-telemetry backend so that it can be scraped.

We also have already defined some alerts to get information about the status of the network https://github.com/w3f/substrate-telemetry-chart/blob/master/charts/substrate-telemetry/templates/alertrules.yaml but the information that we get currently from the exporter is pretty generic and won't be useful at all for knowing how the validators are performing. So the idea is to change the exporter to be configurable to get information about a concrete validator, and then define a set of alertrules for this data.

So, as I see it nothing should be changed in this repo, now that we can configure the telemetry endpoint to be used by the validators we are good. We have started the work on the other two repos to make these validators more observable. closing this issue now, feel free to reopen if you think that it should be handled in a different way :)
