### ISSUE TITLE
Add Digital Ocean VM Option

### ISSUE THREAD

**Issue by retotrinkler** [w3f/polkadot-secure-validator#20]
`Create a new Droplet` should be doable with [one authenticated curl call](https://developers.digitalocean.com/documentation/v2/#droplets).

Eg `curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer b7d03a6947b217efb6f3ec3bd3504582" -d '{"name":"example.com","region":"nyc3","size":"s-1vcpu-1gb","image":"ubuntu-16-04-x64","ssh_keys":[107149],"backups":false,"ipv6":true,"user_data":null,"private_networking":null,"volumes": null,"tags":["web"]}' "https://api.digitalocean.com/v2/droplets" `

Or using [terraform](https://www.terraform.io/docs/providers/do/r/droplet.html).

And then simply applying ansible script

**Comment by fgimenez** [comment]
In order to align with what we already have we should develop a new terraform module similar to these https://github.com/w3f/polkadot-secure-validator/tree/master/terraform. It should define these variables https://github.com/w3f/polkadot-secure-validator/blob/master/terraform/aws/variables.tf (adapted to digital ocean case).
