### ISSUE TITLE
"yarn sync" command erroring

### ISSUE THREAD

**Issue by tgiardina** [w3f/polkadot-secure-validator#28]
Hi all,

I'm following the README instructions, but when I run "yarn sync -c config/main.json," I get the following error:

```
$ yarn sync -c config/main.json
yarn run v1.19.1
$ node . sync -c config/main.json
Syncing platform...
Could not sync platform: EEXIST: file already exists, mkdir '/home/tommy/.config/polkadot-secure-validator/build/w3f/terraform/remote-state0'
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Removing '/home/tommy/.config/polkadot-secure-validator' does not fix this problem.

Any advice would be appreciated!

**Comment by tgiardina** [comment]
If I naively change 
```
fs.mkdirSync(targetDir, {recursive: true});
```
to
```
if(!fs.lstatSync(path.dirname(target)).isDirectory()) {
  fs.mkdirSync(targetDir, {recursive: true});
}
```
at line 17 of secure-validator/src/lib/tpl.js, I get the following error instead:
```
$ yarn sync -c config/main.json
yarn run v1.19.1
$ node . sync -c config/main.json
Syncing platform...
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn terraform ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fgimenez** [comment]
Hi @tgiardina thanks for your interest in the project! :)

Regarding your first error, it happens when you have more than one node version installed in the system, for instance the system-wide node and the instances that can be installed by tools like yarn. To prevent it we recommend using nvm https://github.com/nvm-sh/nvm it allows you to have isolated versions of node installed together at the user level.

The changes you propose in the second comment should not be required, but anyway they expose other problem you will have once the node installation is sorted, you need to have also installed terraform to create the remote machines. Take a look at the prerequisites version for all the required tools https://github.com/w3f/polkadot-secure-validator/#prerequisites

Feel free to reopen if you find any additional issue.

**Comment by tgiardina** [comment]
Thanks for the quick response3 @fgimenez!

Turns out my problem was with Terraform. I had installed it with `sudo snap install terraform`, which doesn't work for some reason. When I installed it via the instructions laid out by [the best answer here](https://askubuntu.com/questions/983351/how-to-install-terraform-in-ubuntu), everything works!

**Comment by znat** [comment]
Hi there,
I am having the exact same issue:
```
yarn run v1.22.4
$ node . sync -c config/main.json
Syncing platform...
Could not sync platform: EEXIST: file already exists, mkdir '/Users/nathanzylbersztejn/Library/Application Support/polkadot-secure-validator/build/Znat/terraform/remote-state0'
```

I am using `nvm` with `lts/fermoium`
I installed Terraform manually (so not from a package manager)

If I remove the folder "remote-state0" I still have the error when I try syncing again.

I am using MacOS BigSur.

Any pointer?
Thanks!
