### ISSUE TITLE
Playbook for upgrading nodes

### ISSUE THREAD

**Issue by ilhanu** [w3f/polkadot-secure-validator#60]
To initially set-up the a secure-validator this tool is perfect, also for updating. But the in the ansible-playbook `main.yml` this goes through all the checks, while everything works as it should. While in a upgrade you just want to upgrade the binary and restart the service 

Can we get a new playbook that just upgrades the nodes, replaces the old binary with the new one as written in the sample file?

**Comment by fgimenez** [comment]
I think it makes sense to have such a playbook, but not as part of this tool. The goal of the tool is to make the actual state of provisioned infrastructure match the desired state defined by the configuration. For that, we need to run both terraform and ansible with all the roles, so that after checking the actual state, any change required to make it match the desired state is executed.


We host several roles in this repo that are not executed as part of the normal workflow, but they will be removed soon. I can ping you when we move them to a separate repo if you are interested in having there that playbook.

**Comment by ilhanu** [comment]
@fgimenez that would be great, some of the playbook in the ansible folder are really handy.
